POST_PROCESSOR = 'post_processor'
PRE_PROCESSOR = 'pre_processor'
FETCH_PROCESSOR = 'fetch_processor'
INDEX_COL = 'index_col'
EVAL_METRIC = 'eval_metric'
LABEL_COLUMN = 'label_column'
LABEL_COLUMN_PRED = 'label_column_pred'
NAME = 'name'
SUBSAMPLE = 'subsample'

TIMESTAMP_STR = 'timestamp'
PREDICTOR = 'predictor'
PROFILE = 'profile'

PROFILE_FAST = 'PROFILE_FAST'
PROFILE_FAST2 = 'PROFILE_FAST2'
PROFILE_FULL_1HR = 'PROFILE_FULL_1HR'
PROFILE_FULL_4HR = 'PROFILE_FULL_4HR'
PROFILE_FULL_8HR = 'PROFILE_FULL_8HR'
PROFILE_FULL_12HR = 'PROFILE_FULL_12HR'
PROFILE_FULL_24HR = 'PROFILE_FULL_24HR'
PROFILE_FULL_32HR = 'PROFILE_FULL_32HR'

PROFILE_FULL = 'PROFILE_FULL'
PROFILE_LEVEL_1_ONLY = 'PROFILE_LEVEL_1_ONLY'
PROFILE_FULL_NO_STACKING_WITH_HPO = 'PROFILE_FULL_NO_STACKING_WITH_HPO'
PROFILE_FULL_WITH_HPO = 'PROFILE_FULL_WITH_HPO'
FITTING_TIME_LIMITS = 'FITTING_TIME_LIMITS'
PROBLEM_TYPE = 'PROBLEM_TYPE'

TAG = 'unk' # default tag when not specified

GCP_PROJECT_ID = 'YOUR_GCP_PROJECT_NAME'
GCP_BUCKET_NAME = 'tabulardata'
GOOGLE_APPLICATION_CREDENTIALS = '/home/ubuntu/YOUR_GCP_KEY.json'
AUTOWEKA_PATH = '~/' # Path to Folder containing lib/autoweka/autoweka.jar installed during install.sh
KAGGLE_CREDENTIALS = '/home/ubuntu/.kaggle/kaggle.json'